// !!! DO NOT EDIT !!! -- automatically generated by scripts/assets.js

import aarch64Original from 'url:../../images/devicon/aarch64-original.svg';
import aarch64Plain from 'url:../../images/devicon/aarch64-plain.svg';
import adonisjsOriginal from 'url:../../images/devicon/adonisjs-original.svg';
import adonisjsOriginalWordmark from 'url:../../images/devicon/adonisjs-original-wordmark.svg';
import aftereffectsOriginal from 'url:../../images/devicon/aftereffects-original.svg';
import aftereffectsPlain from 'url:../../images/devicon/aftereffects-plain.svg';
import amazonwebservicesOriginal from 'url:../../images/devicon/amazonwebservices-original.svg';
import amazonwebservicesOriginalWordmark from 'url:../../images/devicon/amazonwebservices-original-wordmark.svg';
import amazonwebservicesPlainWordmark from 'url:../../images/devicon/amazonwebservices-plain-wordmark.svg';
import anacondaOriginal from 'url:../../images/devicon/anaconda-original.svg';
import anacondaOriginalWordmark from 'url:../../images/devicon/anaconda-original-wordmark.svg';
import androidOriginal from 'url:../../images/devicon/android-original.svg';
import androidOriginalWordmark from 'url:../../images/devicon/android-original-wordmark.svg';
import androidPlain from 'url:../../images/devicon/android-plain.svg';
import androidPlainWordmark from 'url:../../images/devicon/android-plain-wordmark.svg';
import androidstudioOriginal from 'url:../../images/devicon/androidstudio-original.svg';
import androidstudioOriginalWordmark from 'url:../../images/devicon/androidstudio-original-wordmark.svg';
import androidstudioPlain from 'url:../../images/devicon/androidstudio-plain.svg';
import androidstudioPlainWordmark from 'url:../../images/devicon/androidstudio-plain-wordmark.svg';
import angularjsOriginal from 'url:../../images/devicon/angularjs-original.svg';
import angularjsOriginalWordmark from 'url:../../images/devicon/angularjs-original-wordmark.svg';
import angularjsPlain from 'url:../../images/devicon/angularjs-plain.svg';
import angularjsPlainWordmark from 'url:../../images/devicon/angularjs-plain-wordmark.svg';
import ansibleOriginal from 'url:../../images/devicon/ansible-original.svg';
import ansibleOriginalWordmark from 'url:../../images/devicon/ansible-original-wordmark.svg';
import ansiblePlain from 'url:../../images/devicon/ansible-plain.svg';
import ansiblePlainWordmark from 'url:../../images/devicon/ansible-plain-wordmark.svg';
import apacheLine from 'url:../../images/devicon/apache-line.svg';
import apacheLineWordmark from 'url:../../images/devicon/apache-line-wordmark.svg';
import apacheOriginal from 'url:../../images/devicon/apache-original.svg';
import apacheOriginalWordmark from 'url:../../images/devicon/apache-original-wordmark.svg';
import apachePlain from 'url:../../images/devicon/apache-plain.svg';
import apachePlainWordmark from 'url:../../images/devicon/apache-plain-wordmark.svg';
import apachekafkaOriginal from 'url:../../images/devicon/apachekafka-original.svg';
import apachekafkaOriginalWordmark from 'url:../../images/devicon/apachekafka-original-wordmark.svg';
import appceleratorOriginal from 'url:../../images/devicon/appcelerator-original.svg';
import appceleratorOriginalWordmark from 'url:../../images/devicon/appcelerator-original-wordmark.svg';
import appceleratorPlainWordmark from 'url:../../images/devicon/appcelerator-plain-wordmark.svg';
import appleOriginal from 'url:../../images/devicon/apple-original.svg';
import appwriteOriginal from 'url:../../images/devicon/appwrite-original.svg';
import appwriteOriginalWordmark from 'url:../../images/devicon/appwrite-original-wordmark.svg';
import appwritePlain from 'url:../../images/devicon/appwrite-plain.svg';
import appwritePlainWordmark from 'url:../../images/devicon/appwrite-plain-wordmark.svg';
import arduinoOriginal from 'url:../../images/devicon/arduino-original.svg';
import arduinoOriginalWordmark from 'url:../../images/devicon/arduino-original-wordmark.svg';
import arduinoPlain from 'url:../../images/devicon/arduino-plain.svg';
import arduinoPlainWordmark from 'url:../../images/devicon/arduino-plain-wordmark.svg';
import argocdOriginal from 'url:../../images/devicon/argocd-original.svg';
import argocdOriginalWordmark from 'url:../../images/devicon/argocd-original-wordmark.svg';
import argocdPlain from 'url:../../images/devicon/argocd-plain.svg';
import argocdPlainWordmark from 'url:../../images/devicon/argocd-plain-wordmark.svg';
import atomOriginal from 'url:../../images/devicon/atom-original.svg';
import atomOriginalWordmark from 'url:../../images/devicon/atom-original-wordmark.svg';
import azureOriginal from 'url:../../images/devicon/azure-original.svg';
import azureOriginalWordmark from 'url:../../images/devicon/azure-original-wordmark.svg';
import azurePlain from 'url:../../images/devicon/azure-plain.svg';
import azurePlainWordmark from 'url:../../images/devicon/azure-plain-wordmark.svg';
import babelOriginal from 'url:../../images/devicon/babel-original.svg';
import babelPlain from 'url:../../images/devicon/babel-plain.svg';
import backbonejsOriginal from 'url:../../images/devicon/backbonejs-original.svg';
import backbonejsOriginalWordmark from 'url:../../images/devicon/backbonejs-original-wordmark.svg';
import backbonejsPlain from 'url:../../images/devicon/backbonejs-plain.svg';
import backbonejsPlainWordmark from 'url:../../images/devicon/backbonejs-plain-wordmark.svg';
import bambooOriginal from 'url:../../images/devicon/bamboo-original.svg';
import bambooOriginalWordmark from 'url:../../images/devicon/bamboo-original-wordmark.svg';
import bashOriginal from 'url:../../images/devicon/bash-original.svg';
import bashPlain from 'url:../../images/devicon/bash-plain.svg';
import behanceOriginal from 'url:../../images/devicon/behance-original.svg';
import behanceOriginalWordmark from 'url:../../images/devicon/behance-original-wordmark.svg';
import behancePlain from 'url:../../images/devicon/behance-plain.svg';
import behancePlainWordmark from 'url:../../images/devicon/behance-plain-wordmark.svg';
import bitbucketOriginal from 'url:../../images/devicon/bitbucket-original.svg';
import bitbucketOriginalWordmark from 'url:../../images/devicon/bitbucket-original-wordmark.svg';
import blenderOriginal from 'url:../../images/devicon/blender-original.svg';
import blenderOriginalWordmark from 'url:../../images/devicon/blender-original-wordmark.svg';
import bootstrapOriginal from 'url:../../images/devicon/bootstrap-original.svg';
import bootstrapOriginalWordmark from 'url:../../images/devicon/bootstrap-original-wordmark.svg';
import bootstrapPlain from 'url:../../images/devicon/bootstrap-plain.svg';
import bootstrapPlainWordmark from 'url:../../images/devicon/bootstrap-plain-wordmark.svg';
import bowerLine from 'url:../../images/devicon/bower-line.svg';
import bowerLineWordmark from 'url:../../images/devicon/bower-line-wordmark.svg';
import bowerOriginal from 'url:../../images/devicon/bower-original.svg';
import bowerOriginalWordmark from 'url:../../images/devicon/bower-original-wordmark.svg';
import bowerPlain from 'url:../../images/devicon/bower-plain.svg';
import bowerPlainWordmark from 'url:../../images/devicon/bower-plain-wordmark.svg';
import bulmaPlain from 'url:../../images/devicon/bulma-plain.svg';
import cLine from 'url:../../images/devicon/c-line.svg';
import cOriginal from 'url:../../images/devicon/c-original.svg';
import cPlain from 'url:../../images/devicon/c-plain.svg';
import cakephpOriginal from 'url:../../images/devicon/cakephp-original.svg';
import cakephpOriginalWordmark from 'url:../../images/devicon/cakephp-original-wordmark.svg';
import cakephpPlain from 'url:../../images/devicon/cakephp-plain.svg';
import cakephpPlainWordmark from 'url:../../images/devicon/cakephp-plain-wordmark.svg';
import canvaOriginal from 'url:../../images/devicon/canva-original.svg';
import centosOriginal from 'url:../../images/devicon/centos-original.svg';
import centosOriginalWordmark from 'url:../../images/devicon/centos-original-wordmark.svg';
import centosPlain from 'url:../../images/devicon/centos-plain.svg';
import centosPlainWordmark from 'url:../../images/devicon/centos-plain-wordmark.svg';
import ceylonOriginal from 'url:../../images/devicon/ceylon-original.svg';
import ceylonOriginalWordmark from 'url:../../images/devicon/ceylon-original-wordmark.svg';
import ceylonPlain from 'url:../../images/devicon/ceylon-plain.svg';
import ceylonPlainWordmark from 'url:../../images/devicon/ceylon-plain-wordmark.svg';
import chromeOriginal from 'url:../../images/devicon/chrome-original.svg';
import chromeOriginalWordmark from 'url:../../images/devicon/chrome-original-wordmark.svg';
import chromePlain from 'url:../../images/devicon/chrome-plain.svg';
import chromePlainWordmark from 'url:../../images/devicon/chrome-plain-wordmark.svg';
import circleciPlain from 'url:../../images/devicon/circleci-plain.svg';
import circleciPlainWordmark from 'url:../../images/devicon/circleci-plain-wordmark.svg';
import clojureLine from 'url:../../images/devicon/clojure-line.svg';
import clojureOriginal from 'url:../../images/devicon/clojure-original.svg';
import clojurescriptOriginal from 'url:../../images/devicon/clojurescript-original.svg';
import clojurescriptPlain from 'url:../../images/devicon/clojurescript-plain.svg';
import cmakeOriginal from 'url:../../images/devicon/cmake-original.svg';
import cmakeOriginalWordmark from 'url:../../images/devicon/cmake-original-wordmark.svg';
import cmakePlain from 'url:../../images/devicon/cmake-plain.svg';
import cmakePlainWordmark from 'url:../../images/devicon/cmake-plain-wordmark.svg';
import codecovPlain from 'url:../../images/devicon/codecov-plain.svg';
import codeigniterPlain from 'url:../../images/devicon/codeigniter-plain.svg';
import codeigniterPlainWordmark from 'url:../../images/devicon/codeigniter-plain-wordmark.svg';
import codepenOriginalWordmark from 'url:../../images/devicon/codepen-original-wordmark.svg';
import codepenPlain from 'url:../../images/devicon/codepen-plain.svg';
import coffeescriptOriginal from 'url:../../images/devicon/coffeescript-original.svg';
import coffeescriptOriginalWordmark from 'url:../../images/devicon/coffeescript-original-wordmark.svg';
import composerLine from 'url:../../images/devicon/composer-line.svg';
import composerLineWordmark from 'url:../../images/devicon/composer-line-wordmark.svg';
import composerOriginal from 'url:../../images/devicon/composer-original.svg';
import confluenceOriginal from 'url:../../images/devicon/confluence-original.svg';
import confluenceOriginalWordmark from 'url:../../images/devicon/confluence-original-wordmark.svg';
import couchdbOriginal from 'url:../../images/devicon/couchdb-original.svg';
import couchdbOriginalWordmark from 'url:../../images/devicon/couchdb-original-wordmark.svg';
import couchdbPlain from 'url:../../images/devicon/couchdb-plain.svg';
import couchdbPlainWordmark from 'url:../../images/devicon/couchdb-plain-wordmark.svg';
import cplusplusLine from 'url:../../images/devicon/cplusplus-line.svg';
import cplusplusOriginal from 'url:../../images/devicon/cplusplus-original.svg';
import cplusplusPlain from 'url:../../images/devicon/cplusplus-plain.svg';
import crystalOriginal from 'url:../../images/devicon/crystal-original.svg';
import crystalOriginalWordmark from 'url:../../images/devicon/crystal-original-wordmark.svg';
import csharpLine from 'url:../../images/devicon/csharp-line.svg';
import csharpOriginal from 'url:../../images/devicon/csharp-original.svg';
import csharpPlain from 'url:../../images/devicon/csharp-plain.svg';
import css3Original from 'url:../../images/devicon/css3-original.svg';
import css3OriginalWordmark from 'url:../../images/devicon/css3-original-wordmark.svg';
import css3Plain from 'url:../../images/devicon/css3-plain.svg';
import css3PlainWordmark from 'url:../../images/devicon/css3-plain-wordmark.svg';
import cucumberPlain from 'url:../../images/devicon/cucumber-plain.svg';
import cucumberPlainWordmark from 'url:../../images/devicon/cucumber-plain-wordmark.svg';
import d3JsOriginal from 'url:../../images/devicon/d3js-original.svg';
import d3JsPlain from 'url:../../images/devicon/d3js-plain.svg';
import dartOriginal from 'url:../../images/devicon/dart-original.svg';
import dartOriginalWordmark from 'url:../../images/devicon/dart-original-wordmark.svg';
import dartPlain from 'url:../../images/devicon/dart-plain.svg';
import dartPlainWordmark from 'url:../../images/devicon/dart-plain-wordmark.svg';
import debianOriginal from 'url:../../images/devicon/debian-original.svg';
import debianOriginalWordmark from 'url:../../images/devicon/debian-original-wordmark.svg';
import debianPlain from 'url:../../images/devicon/debian-plain.svg';
import debianPlainWordmark from 'url:../../images/devicon/debian-plain-wordmark.svg';
import denojsOriginal from 'url:../../images/devicon/denojs-original.svg';
import denojsOriginalWordmark from 'url:../../images/devicon/denojs-original-wordmark.svg';
import deviconLine from 'url:../../images/devicon/devicon-line.svg';
import deviconLineWordmark from 'url:../../images/devicon/devicon-line-wordmark.svg';
import deviconOriginal from 'url:../../images/devicon/devicon-original.svg';
import deviconOriginalWordmark from 'url:../../images/devicon/devicon-original-wordmark.svg';
import deviconPlain from 'url:../../images/devicon/devicon-plain.svg';
import deviconPlainWordmark from 'url:../../images/devicon/devicon-plain-wordmark.svg';
import digitaloceanOriginal from 'url:../../images/devicon/digitalocean-original.svg';
import digitaloceanOriginalWordmark from 'url:../../images/devicon/digitalocean-original-wordmark.svg';
import digitaloceanPlain from 'url:../../images/devicon/digitalocean-plain.svg';
import digitaloceanPlainWordmark from 'url:../../images/devicon/digitalocean-plain-wordmark.svg';
import discordjsOriginal from 'url:../../images/devicon/discordjs-original.svg';
import discordjsOriginalWordmark from 'url:../../images/devicon/discordjs-original-wordmark.svg';
import discordjsPlain from 'url:../../images/devicon/discordjs-plain.svg';
import discordjsPlainWordmark from 'url:../../images/devicon/discordjs-plain-wordmark.svg';
import djangoPlain from 'url:../../images/devicon/django-plain.svg';
import djangoPlainWordmark from 'url:../../images/devicon/django-plain-wordmark.svg';
import dockerOriginal from 'url:../../images/devicon/docker-original.svg';
import dockerOriginalWordmark from 'url:../../images/devicon/docker-original-wordmark.svg';
import dockerPlain from 'url:../../images/devicon/docker-plain.svg';
import dockerPlainWordmark from 'url:../../images/devicon/docker-plain-wordmark.svg';
import doctrineLine from 'url:../../images/devicon/doctrine-line.svg';
import doctrineLineWordmark from 'url:../../images/devicon/doctrine-line-wordmark.svg';
import doctrineOriginal from 'url:../../images/devicon/doctrine-original.svg';
import doctrineOriginalWordmark from 'url:../../images/devicon/doctrine-original-wordmark.svg';
import doctrinePlain from 'url:../../images/devicon/doctrine-plain.svg';
import doctrinePlainWordmark from 'url:../../images/devicon/doctrine-plain-wordmark.svg';
import dotNetOriginal from 'url:../../images/devicon/dot-net-original.svg';
import dotNetOriginalWordmark from 'url:../../images/devicon/dot-net-original-wordmark.svg';
import dotNetPlain from 'url:../../images/devicon/dot-net-plain.svg';
import dotNetPlainWordmark from 'url:../../images/devicon/dot-net-plain-wordmark.svg';
import dotnetcoreOriginal from 'url:../../images/devicon/dotnetcore-original.svg';
import dotnetcorePlain from 'url:../../images/devicon/dotnetcore-plain.svg';
import dropwizardOriginal from 'url:../../images/devicon/dropwizard-original.svg';
import dropwizardPlain from 'url:../../images/devicon/dropwizard-plain.svg';
import drupalOriginal from 'url:../../images/devicon/drupal-original.svg';
import drupalOriginalWordmark from 'url:../../images/devicon/drupal-original-wordmark.svg';
import drupalPlain from 'url:../../images/devicon/drupal-plain.svg';
import drupalPlainWordmark from 'url:../../images/devicon/drupal-plain-wordmark.svg';
import electronOriginal from 'url:../../images/devicon/electron-original.svg';
import electronOriginalWordmark from 'url:../../images/devicon/electron-original-wordmark.svg';
import eleventyOriginal from 'url:../../images/devicon/eleventy-original.svg';
import eleventyPlain from 'url:../../images/devicon/eleventy-plain.svg';
import elixirOriginal from 'url:../../images/devicon/elixir-original.svg';
import elixirOriginalWordmark from 'url:../../images/devicon/elixir-original-wordmark.svg';
import elixirPlain from 'url:../../images/devicon/elixir-plain.svg';
import elixirPlainWordmark from 'url:../../images/devicon/elixir-plain-wordmark.svg';
import elmOriginal from 'url:../../images/devicon/elm-original.svg';
import elmOriginalWordmark from 'url:../../images/devicon/elm-original-wordmark.svg';
import elmPlain from 'url:../../images/devicon/elm-plain.svg';
import elmPlainWordmark from 'url:../../images/devicon/elm-plain-wordmark.svg';
import embeddedcOriginal from 'url:../../images/devicon/embeddedc-original.svg';
import embeddedcOriginalWordmark from 'url:../../images/devicon/embeddedc-original-wordmark.svg';
import embeddedcPlain from 'url:../../images/devicon/embeddedc-plain.svg';
import embeddedcPlainWordmark from 'url:../../images/devicon/embeddedc-plain-wordmark.svg';
import emberOriginalWordmark from 'url:../../images/devicon/ember-original-wordmark.svg';
import erlangOriginal from 'url:../../images/devicon/erlang-original.svg';
import erlangOriginalWordmark from 'url:../../images/devicon/erlang-original-wordmark.svg';
import erlangPlain from 'url:../../images/devicon/erlang-plain.svg';
import erlangPlainWordmark from 'url:../../images/devicon/erlang-plain-wordmark.svg';
import eslintOriginal from 'url:../../images/devicon/eslint-original.svg';
import eslintOriginalWordmark from 'url:../../images/devicon/eslint-original-wordmark.svg';
import expressOriginal from 'url:../../images/devicon/express-original.svg';
import expressOriginalWordmark from 'url:../../images/devicon/express-original-wordmark.svg';
import facebookOriginal from 'url:../../images/devicon/facebook-original.svg';
import facebookPlain from 'url:../../images/devicon/facebook-plain.svg';
import fastapiOriginal from 'url:../../images/devicon/fastapi-original.svg';
import fastapiOriginalWordmark from 'url:../../images/devicon/fastapi-original-wordmark.svg';
import fastapiPlain from 'url:../../images/devicon/fastapi-plain.svg';
import fastapiPlainWordmark from 'url:../../images/devicon/fastapi-plain-wordmark.svg';
import feathersjsOriginal from 'url:../../images/devicon/feathersjs-original.svg';
import fedoraOriginal from 'url:../../images/devicon/fedora-original.svg';
import fedoraPlain from 'url:../../images/devicon/fedora-plain.svg';
import figmaOriginal from 'url:../../images/devicon/figma-original.svg';
import figmaPlain from 'url:../../images/devicon/figma-plain.svg';
import filezillaPlain from 'url:../../images/devicon/filezilla-plain.svg';
import filezillaPlainWordmark from 'url:../../images/devicon/filezilla-plain-wordmark.svg';
import firebasePlain from 'url:../../images/devicon/firebase-plain.svg';
import firebasePlainWordmark from 'url:../../images/devicon/firebase-plain-wordmark.svg';
import firefoxOriginal from 'url:../../images/devicon/firefox-original.svg';
import firefoxOriginalWordmark from 'url:../../images/devicon/firefox-original-wordmark.svg';
import firefoxPlain from 'url:../../images/devicon/firefox-plain.svg';
import firefoxPlainWordmark from 'url:../../images/devicon/firefox-plain-wordmark.svg';
import flaskOriginal from 'url:../../images/devicon/flask-original.svg';
import flaskOriginalWordmark from 'url:../../images/devicon/flask-original-wordmark.svg';
import flutterOriginal from 'url:../../images/devicon/flutter-original.svg';
import flutterPlain from 'url:../../images/devicon/flutter-plain.svg';
import foundationOriginal from 'url:../../images/devicon/foundation-original.svg';
import foundationOriginalWordmark from 'url:../../images/devicon/foundation-original-wordmark.svg';
import foundationPlain from 'url:../../images/devicon/foundation-plain.svg';
import foundationPlainWordmark from 'url:../../images/devicon/foundation-plain-wordmark.svg';
import fsharpOriginal from 'url:../../images/devicon/fsharp-original.svg';
import fsharpPlain from 'url:../../images/devicon/fsharp-plain.svg';
import gatlingPlain from 'url:../../images/devicon/gatling-plain.svg';
import gatlingPlainWordmark from 'url:../../images/devicon/gatling-plain-wordmark.svg';
import gatsbyOriginal from 'url:../../images/devicon/gatsby-original.svg';
import gatsbyOriginalWordmark from 'url:../../images/devicon/gatsby-original-wordmark.svg';
import gatsbyPlain from 'url:../../images/devicon/gatsby-plain.svg';
import gatsbyPlainWordmark from 'url:../../images/devicon/gatsby-plain-wordmark.svg';
import gccOriginal from 'url:../../images/devicon/gcc-original.svg';
import gccPlain from 'url:../../images/devicon/gcc-plain.svg';
import gentooPlain from 'url:../../images/devicon/gentoo-plain.svg';
import gentooPlainWordmark from 'url:../../images/devicon/gentoo-plain-wordmark.svg';
import gimpOriginal from 'url:../../images/devicon/gimp-original.svg';
import gimpOriginalWordmark from 'url:../../images/devicon/gimp-original-wordmark.svg';
import gimpPlain from 'url:../../images/devicon/gimp-plain.svg';
import gimpPlainWordmark from 'url:../../images/devicon/gimp-plain-wordmark.svg';
import gitOriginal from 'url:../../images/devicon/git-original.svg';
import gitOriginalWordmark from 'url:../../images/devicon/git-original-wordmark.svg';
import gitPlain from 'url:../../images/devicon/git-plain.svg';
import gitPlainWordmark from 'url:../../images/devicon/git-plain-wordmark.svg';
import githubOriginal from 'url:../../images/devicon/github-original.svg';
import githubOriginalWordmark from 'url:../../images/devicon/github-original-wordmark.svg';
import gitlabOriginal from 'url:../../images/devicon/gitlab-original.svg';
import gitlabOriginalWordmark from 'url:../../images/devicon/gitlab-original-wordmark.svg';
import gitlabPlain from 'url:../../images/devicon/gitlab-plain.svg';
import gitlabPlainWordmark from 'url:../../images/devicon/gitlab-plain-wordmark.svg';
import gitterPlain from 'url:../../images/devicon/gitter-plain.svg';
import gitterPlainWordmark from 'url:../../images/devicon/gitter-plain-wordmark.svg';
import goLine from 'url:../../images/devicon/go-line.svg';
import goOriginal from 'url:../../images/devicon/go-original.svg';
import goOriginalWordmark from 'url:../../images/devicon/go-original-wordmark.svg';
import goPlain from 'url:../../images/devicon/go-plain.svg';
import godotOriginal from 'url:../../images/devicon/godot-original.svg';
import godotOriginalWordmark from 'url:../../images/devicon/godot-original-wordmark.svg';
import godotPlain from 'url:../../images/devicon/godot-plain.svg';
import godotPlainWordmark from 'url:../../images/devicon/godot-plain-wordmark.svg';
import googleOriginal from 'url:../../images/devicon/google-original.svg';
import googleOriginalWordmark from 'url:../../images/devicon/google-original-wordmark.svg';
import googlePlain from 'url:../../images/devicon/google-plain.svg';
import googlePlainWordmark from 'url:../../images/devicon/google-plain-wordmark.svg';
import googlecloudOriginal from 'url:../../images/devicon/googlecloud-original.svg';
import googlecloudOriginalWordmark from 'url:../../images/devicon/googlecloud-original-wordmark.svg';
import googlecloudPlain from 'url:../../images/devicon/googlecloud-plain.svg';
import googlecloudPlainWordmark from 'url:../../images/devicon/googlecloud-plain-wordmark.svg';
import gradlePlain from 'url:../../images/devicon/gradle-plain.svg';
import gradlePlainWordmark from 'url:../../images/devicon/gradle-plain-wordmark.svg';
import grafanaOriginal from 'url:../../images/devicon/grafana-original.svg';
import grafanaOriginalWordmark from 'url:../../images/devicon/grafana-original-wordmark.svg';
import grailsOriginal from 'url:../../images/devicon/grails-original.svg';
import grailsPlain from 'url:../../images/devicon/grails-plain.svg';
import graphqlPlain from 'url:../../images/devicon/graphql-plain.svg';
import graphqlPlainWordmark from 'url:../../images/devicon/graphql-plain-wordmark.svg';
import groovyOriginal from 'url:../../images/devicon/groovy-original.svg';
import groovyPlain from 'url:../../images/devicon/groovy-plain.svg';
import gruntLine from 'url:../../images/devicon/grunt-line.svg';
import gruntLineWordmark from 'url:../../images/devicon/grunt-line-wordmark.svg';
import gruntOriginal from 'url:../../images/devicon/grunt-original.svg';
import gruntOriginalWordmark from 'url:../../images/devicon/grunt-original-wordmark.svg';
import gruntPlain from 'url:../../images/devicon/grunt-plain.svg';
import gruntPlainWordmark from 'url:../../images/devicon/grunt-plain-wordmark.svg';
import gulpPlain from 'url:../../images/devicon/gulp-plain.svg';
import handlebarsOriginal from 'url:../../images/devicon/handlebars-original.svg';
import handlebarsOriginalWordmark from 'url:../../images/devicon/handlebars-original-wordmark.svg';
import haskellOriginal from 'url:../../images/devicon/haskell-original.svg';
import haskellOriginalWordmark from 'url:../../images/devicon/haskell-original-wordmark.svg';
import haskellPlain from 'url:../../images/devicon/haskell-plain.svg';
import haskellPlainWordmark from 'url:../../images/devicon/haskell-plain-wordmark.svg';
import haxeOriginal from 'url:../../images/devicon/haxe-original.svg';
import haxePlain from 'url:../../images/devicon/haxe-plain.svg';
import herokuOriginal from 'url:../../images/devicon/heroku-original.svg';
import herokuOriginalWordmark from 'url:../../images/devicon/heroku-original-wordmark.svg';
import herokuPlain from 'url:../../images/devicon/heroku-plain.svg';
import herokuPlainWordmark from 'url:../../images/devicon/heroku-plain-wordmark.svg';
import html5Original from 'url:../../images/devicon/html5-original.svg';
import html5OriginalWordmark from 'url:../../images/devicon/html5-original-wordmark.svg';
import html5Plain from 'url:../../images/devicon/html5-plain.svg';
import html5PlainWordmark from 'url:../../images/devicon/html5-plain-wordmark.svg';
import hugoOriginal from 'url:../../images/devicon/hugo-original.svg';
import hugoOriginalWordmark from 'url:../../images/devicon/hugo-original-wordmark.svg';
import hugoPlain from 'url:../../images/devicon/hugo-plain.svg';
import hugoPlainWordmark from 'url:../../images/devicon/hugo-plain-wordmark.svg';
import ie10Original from 'url:../../images/devicon/ie10-original.svg';
import iftttOriginal from 'url:../../images/devicon/ifttt-original.svg';
import illustratorLine from 'url:../../images/devicon/illustrator-line.svg';
import illustratorPlain from 'url:../../images/devicon/illustrator-plain.svg';
import inkscapeOriginal from 'url:../../images/devicon/inkscape-original.svg';
import inkscapeOriginalWordmark from 'url:../../images/devicon/inkscape-original-wordmark.svg';
import inkscapePlain from 'url:../../images/devicon/inkscape-plain.svg';
import inkscapePlainWordmark from 'url:../../images/devicon/inkscape-plain-wordmark.svg';
import intellijOriginal from 'url:../../images/devicon/intellij-original.svg';
import intellijOriginalWordmark from 'url:../../images/devicon/intellij-original-wordmark.svg';
import intellijPlain from 'url:../../images/devicon/intellij-plain.svg';
import intellijPlainWordmark from 'url:../../images/devicon/intellij-plain-wordmark.svg';
import ionicOriginal from 'url:../../images/devicon/ionic-original.svg';
import ionicOriginalWordmark from 'url:../../images/devicon/ionic-original-wordmark.svg';
import jamstackOriginal from 'url:../../images/devicon/jamstack-original.svg';
import jamstackOriginalWordmark from 'url:../../images/devicon/jamstack-original-wordmark.svg';
import jamstackPlainWordmark from 'url:../../images/devicon/jamstack-plain-wordmark.svg';
import jasminePlain from 'url:../../images/devicon/jasmine-plain.svg';
import jasminePlainWordmark from 'url:../../images/devicon/jasmine-plain-wordmark.svg';
import javaOriginal from 'url:../../images/devicon/java-original.svg';
import javaOriginalWordmark from 'url:../../images/devicon/java-original-wordmark.svg';
import javaPlain from 'url:../../images/devicon/java-plain.svg';
import javaPlainWordmark from 'url:../../images/devicon/java-plain-wordmark.svg';
import javascriptOriginal from 'url:../../images/devicon/javascript-original.svg';
import javascriptPlain from 'url:../../images/devicon/javascript-plain.svg';
import jeetOriginal from 'url:../../images/devicon/jeet-original.svg';
import jeetOriginalWordmark from 'url:../../images/devicon/jeet-original-wordmark.svg';
import jeetPlain from 'url:../../images/devicon/jeet-plain.svg';
import jeetPlainWordmark from 'url:../../images/devicon/jeet-plain-wordmark.svg';
import jenkinsLine from 'url:../../images/devicon/jenkins-line.svg';
import jenkinsOriginal from 'url:../../images/devicon/jenkins-original.svg';
import jenkinsPlain from 'url:../../images/devicon/jenkins-plain.svg';
import jestPlain from 'url:../../images/devicon/jest-plain.svg';
import jetbrainsOriginal from 'url:../../images/devicon/jetbrains-original.svg';
import jetbrainsPlain from 'url:../../images/devicon/jetbrains-plain.svg';
import jiraOriginal from 'url:../../images/devicon/jira-original.svg';
import jiraOriginalWordmark from 'url:../../images/devicon/jira-original-wordmark.svg';
import jiraPlain from 'url:../../images/devicon/jira-plain.svg';
import jiraPlainWordmark from 'url:../../images/devicon/jira-plain-wordmark.svg';
import jqueryOriginal from 'url:../../images/devicon/jquery-original.svg';
import jqueryOriginalWordmark from 'url:../../images/devicon/jquery-original-wordmark.svg';
import jqueryPlain from 'url:../../images/devicon/jquery-plain.svg';
import jqueryPlainWordmark from 'url:../../images/devicon/jquery-plain-wordmark.svg';
import juliaOriginal from 'url:../../images/devicon/julia-original.svg';
import juliaOriginalWordmark from 'url:../../images/devicon/julia-original-wordmark.svg';
import juliaPlain from 'url:../../images/devicon/julia-plain.svg';
import juliaPlainWordmark from 'url:../../images/devicon/julia-plain-wordmark.svg';
import jupyterOriginal from 'url:../../images/devicon/jupyter-original.svg';
import jupyterOriginalWordmark from 'url:../../images/devicon/jupyter-original-wordmark.svg';
import jupyterPlain from 'url:../../images/devicon/jupyter-plain.svg';
import jupyterPlainWordmark from 'url:../../images/devicon/jupyter-plain-wordmark.svg';
import k3SOriginal from 'url:../../images/devicon/k3s-original.svg';
import k3SOriginalWordmark from 'url:../../images/devicon/k3s-original-wordmark.svg';
import k3SPlainWordmark from 'url:../../images/devicon/k3s-plain-wordmark.svg';
import kaggleOriginal from 'url:../../images/devicon/kaggle-original.svg';
import kaggleOriginalWordmark from 'url:../../images/devicon/kaggle-original-wordmark.svg';
import karmaOriginal from 'url:../../images/devicon/karma-original.svg';
import karmaPlain from 'url:../../images/devicon/karma-plain.svg';
import knockoutPlainWordmark from 'url:../../images/devicon/knockout-plain-wordmark.svg';
import kotlinOriginal from 'url:../../images/devicon/kotlin-original.svg';
import kotlinOriginalWordmark from 'url:../../images/devicon/kotlin-original-wordmark.svg';
import kotlinPlain from 'url:../../images/devicon/kotlin-plain.svg';
import kotlinPlainWordmark from 'url:../../images/devicon/kotlin-plain-wordmark.svg';
import krakenjsOriginal from 'url:../../images/devicon/krakenjs-original.svg';
import krakenjsOriginalWordmark from 'url:../../images/devicon/krakenjs-original-wordmark.svg';
import krakenjsPlain from 'url:../../images/devicon/krakenjs-plain.svg';
import krakenjsPlainWordmark from 'url:../../images/devicon/krakenjs-plain-wordmark.svg';
import kubernetesPlain from 'url:../../images/devicon/kubernetes-plain.svg';
import kubernetesPlainWordmark from 'url:../../images/devicon/kubernetes-plain-wordmark.svg';
import labviewOriginal from 'url:../../images/devicon/labview-original.svg';
import labviewOriginalWordmark from 'url:../../images/devicon/labview-original-wordmark.svg';
import labviewPlain from 'url:../../images/devicon/labview-plain.svg';
import labviewPlainWordmark from 'url:../../images/devicon/labview-plain-wordmark.svg';
import laravelPlain from 'url:../../images/devicon/laravel-plain.svg';
import laravelPlainWordmark from 'url:../../images/devicon/laravel-plain-wordmark.svg';
import latexOriginal from 'url:../../images/devicon/latex-original.svg';
import lessPlainWordmark from 'url:../../images/devicon/less-plain-wordmark.svg';
import linkedinOriginal from 'url:../../images/devicon/linkedin-original.svg';
import linkedinOriginalWordmark from 'url:../../images/devicon/linkedin-original-wordmark.svg';
import linkedinPlain from 'url:../../images/devicon/linkedin-plain.svg';
import linkedinPlainWordmark from 'url:../../images/devicon/linkedin-plain-wordmark.svg';
import linuxOriginal from 'url:../../images/devicon/linux-original.svg';
import linuxPlain from 'url:../../images/devicon/linux-plain.svg';
import luaOriginal from 'url:../../images/devicon/lua-original.svg';
import luaOriginalWordmark from 'url:../../images/devicon/lua-original-wordmark.svg';
import luaPlain from 'url:../../images/devicon/lua-plain.svg';
import luaPlainWordmark from 'url:../../images/devicon/lua-plain-wordmark.svg';
import magentoLine from 'url:../../images/devicon/magento-line.svg';
import magentoOriginal from 'url:../../images/devicon/magento-original.svg';
import magentoOriginalWordmark from 'url:../../images/devicon/magento-original-wordmark.svg';
import markdownOriginal from 'url:../../images/devicon/markdown-original.svg';
import materialuiOriginal from 'url:../../images/devicon/materialui-original.svg';
import materialuiPlain from 'url:../../images/devicon/materialui-plain.svg';
import matlabLine from 'url:../../images/devicon/matlab-line.svg';
import matlabOriginal from 'url:../../images/devicon/matlab-original.svg';
import matlabPlain from 'url:../../images/devicon/matlab-plain.svg';
import mayaOriginal from 'url:../../images/devicon/maya-original.svg';
import mayaOriginalWordmark from 'url:../../images/devicon/maya-original-wordmark.svg';
import mayaPlain from 'url:../../images/devicon/maya-plain.svg';
import mayaPlainWordmark from 'url:../../images/devicon/maya-plain-wordmark.svg';
import meteorOriginal from 'url:../../images/devicon/meteor-original.svg';
import meteorOriginalWordmark from 'url:../../images/devicon/meteor-original-wordmark.svg';
import meteorPlain from 'url:../../images/devicon/meteor-plain.svg';
import meteorPlainWordmark from 'url:../../images/devicon/meteor-plain-wordmark.svg';
import microsoftsqlserverPlain from 'url:../../images/devicon/microsoftsqlserver-plain.svg';
import microsoftsqlserverPlainWordmark from 'url:../../images/devicon/microsoftsqlserver-plain-wordmark.svg';
import minitabOriginal from 'url:../../images/devicon/minitab-original.svg';
import minitabPlain from 'url:../../images/devicon/minitab-plain.svg';
import mochaPlain from 'url:../../images/devicon/mocha-plain.svg';
import modxOriginal from 'url:../../images/devicon/modx-original.svg';
import modxOriginalWordmark from 'url:../../images/devicon/modx-original-wordmark.svg';
import modxPlain from 'url:../../images/devicon/modx-plain.svg';
import modxPlainWordmark from 'url:../../images/devicon/modx-plain-wordmark.svg';
import mongodbOriginal from 'url:../../images/devicon/mongodb-original.svg';
import mongodbOriginalWordmark from 'url:../../images/devicon/mongodb-original-wordmark.svg';
import mongodbPlain from 'url:../../images/devicon/mongodb-plain.svg';
import mongodbPlainWordmark from 'url:../../images/devicon/mongodb-plain-wordmark.svg';
import moodleOriginal from 'url:../../images/devicon/moodle-original.svg';
import moodleOriginalWordmark from 'url:../../images/devicon/moodle-original-wordmark.svg';
import moodlePlain from 'url:../../images/devicon/moodle-plain.svg';
import moodlePlainWordmark from 'url:../../images/devicon/moodle-plain-wordmark.svg';
import msdosLine from 'url:../../images/devicon/msdos-line.svg';
import msdosOriginal from 'url:../../images/devicon/msdos-original.svg';
import msdosPlain from 'url:../../images/devicon/msdos-plain.svg';
import mysqlOriginal from 'url:../../images/devicon/mysql-original.svg';
import mysqlOriginalWordmark from 'url:../../images/devicon/mysql-original-wordmark.svg';
import mysqlPlain from 'url:../../images/devicon/mysql-plain.svg';
import mysqlPlainWordmark from 'url:../../images/devicon/mysql-plain-wordmark.svg';
import neo4JOriginal from 'url:../../images/devicon/neo4j-original.svg';
import neo4JOriginalWordmark from 'url:../../images/devicon/neo4j-original-wordmark.svg';
import neo4JPlain from 'url:../../images/devicon/neo4j-plain.svg';
import neo4JPlainWordmark from 'url:../../images/devicon/neo4j-plain-wordmark.svg';
import nestjsPlain from 'url:../../images/devicon/nestjs-plain.svg';
import nestjsPlainWordmark from 'url:../../images/devicon/nestjs-plain-wordmark.svg';
import networkxOriginal from 'url:../../images/devicon/networkx-original.svg';
import nextjsLine from 'url:../../images/devicon/nextjs-line.svg';
import nextjsOriginal from 'url:../../images/devicon/nextjs-original.svg';
import nextjsOriginalWordmark from 'url:../../images/devicon/nextjs-original-wordmark.svg';
import nginxOriginal from 'url:../../images/devicon/nginx-original.svg';
import nixosOriginal from 'url:../../images/devicon/nixos-original.svg';
import nixosOriginalWordmark from 'url:../../images/devicon/nixos-original-wordmark.svg';
import nixosPlain from 'url:../../images/devicon/nixos-plain.svg';
import nixosPlainWordmark from 'url:../../images/devicon/nixos-plain-wordmark.svg';
import nodejsOriginal from 'url:../../images/devicon/nodejs-original.svg';
import nodejsOriginalWordmark from 'url:../../images/devicon/nodejs-original-wordmark.svg';
import nodejsPlain from 'url:../../images/devicon/nodejs-plain.svg';
import nodejsPlainWordmark from 'url:../../images/devicon/nodejs-plain-wordmark.svg';
import nodewebkitLine from 'url:../../images/devicon/nodewebkit-line.svg';
import nodewebkitLineWordmark from 'url:../../images/devicon/nodewebkit-line-wordmark.svg';
import nodewebkitOriginal from 'url:../../images/devicon/nodewebkit-original.svg';
import nodewebkitOriginalWordmark from 'url:../../images/devicon/nodewebkit-original-wordmark.svg';
import nodewebkitPlain from 'url:../../images/devicon/nodewebkit-plain.svg';
import nodewebkitPlainWordmark from 'url:../../images/devicon/nodewebkit-plain-wordmark.svg';
import npmOriginalWordmark from 'url:../../images/devicon/npm-original-wordmark.svg';
import nugetOriginal from 'url:../../images/devicon/nuget-original.svg';
import nugetOriginalWordmark from 'url:../../images/devicon/nuget-original-wordmark.svg';
import numpyOriginal from 'url:../../images/devicon/numpy-original.svg';
import numpyOriginalWordmark from 'url:../../images/devicon/numpy-original-wordmark.svg';
import nuxtjsOriginal from 'url:../../images/devicon/nuxtjs-original.svg';
import nuxtjsOriginalWordmark from 'url:../../images/devicon/nuxtjs-original-wordmark.svg';
import nuxtjsPlain from 'url:../../images/devicon/nuxtjs-plain.svg';
import nuxtjsPlainWordmark from 'url:../../images/devicon/nuxtjs-plain-wordmark.svg';
import objectivecPlain from 'url:../../images/devicon/objectivec-plain.svg';
import ocamlOriginal from 'url:../../images/devicon/ocaml-original.svg';
import ocamlOriginalWordmark from 'url:../../images/devicon/ocaml-original-wordmark.svg';
import ocamlPlain from 'url:../../images/devicon/ocaml-plain.svg';
import ocamlPlainWordmark from 'url:../../images/devicon/ocaml-plain-wordmark.svg';
import openalOriginal from 'url:../../images/devicon/openal-original.svg';
import openalPlain from 'url:../../images/devicon/openal-plain.svg';
import opencvOriginal from 'url:../../images/devicon/opencv-original.svg';
import opencvOriginalWordmark from 'url:../../images/devicon/opencv-original-wordmark.svg';
import opencvPlain from 'url:../../images/devicon/opencv-plain.svg';
import opencvPlainWordmark from 'url:../../images/devicon/opencv-plain-wordmark.svg';
import openglOriginal from 'url:../../images/devicon/opengl-original.svg';
import openglPlain from 'url:../../images/devicon/opengl-plain.svg';
import opensuseOriginal from 'url:../../images/devicon/opensuse-original.svg';
import opensuseOriginalWordmark from 'url:../../images/devicon/opensuse-original-wordmark.svg';
import opensusePlain from 'url:../../images/devicon/opensuse-plain.svg';
import opensusePlainWordmark from 'url:../../images/devicon/opensuse-plain-wordmark.svg';
import operaOriginal from 'url:../../images/devicon/opera-original.svg';
import operaOriginalWordmark from 'url:../../images/devicon/opera-original-wordmark.svg';
import operaPlain from 'url:../../images/devicon/opera-plain.svg';
import operaPlainWordmark from 'url:../../images/devicon/opera-plain-wordmark.svg';
import oracleOriginal from 'url:../../images/devicon/oracle-original.svg';
import packerOriginal from 'url:../../images/devicon/packer-original.svg';
import packerOriginalWordmark from 'url:../../images/devicon/packer-original-wordmark.svg';
import pandasOriginal from 'url:../../images/devicon/pandas-original.svg';
import pandasOriginalWordmark from 'url:../../images/devicon/pandas-original-wordmark.svg';
import perlOriginal from 'url:../../images/devicon/perl-original.svg';
import perlPlain from 'url:../../images/devicon/perl-plain.svg';
import phalconOriginal from 'url:../../images/devicon/phalcon-original.svg';
import phalconPlain from 'url:../../images/devicon/phalcon-plain.svg';
import phoenixOriginal from 'url:../../images/devicon/phoenix-original.svg';
import phoenixOriginalWordmark from 'url:../../images/devicon/phoenix-original-wordmark.svg';
import phoenixPlain from 'url:../../images/devicon/phoenix-plain.svg';
import phoenixPlainWordmark from 'url:../../images/devicon/phoenix-plain-wordmark.svg';
import photoshopLine from 'url:../../images/devicon/photoshop-line.svg';
import photoshopPlain from 'url:../../images/devicon/photoshop-plain.svg';
import phpOriginal from 'url:../../images/devicon/php-original.svg';
import phpPlain from 'url:../../images/devicon/php-plain.svg';
import phpstormOriginal from 'url:../../images/devicon/phpstorm-original.svg';
import phpstormOriginalWordmark from 'url:../../images/devicon/phpstorm-original-wordmark.svg';
import phpstormPlain from 'url:../../images/devicon/phpstorm-plain.svg';
import phpstormPlainWordmark from 'url:../../images/devicon/phpstorm-plain-wordmark.svg';
import podmanOriginal from 'url:../../images/devicon/podman-original.svg';
import podmanOriginalWordmark from 'url:../../images/devicon/podman-original-wordmark.svg';
import podmanPlain from 'url:../../images/devicon/podman-plain.svg';
import podmanPlainWordmark from 'url:../../images/devicon/podman-plain-wordmark.svg';
import polygonOriginal from 'url:../../images/devicon/polygon-original.svg';
import polygonPlain from 'url:../../images/devicon/polygon-plain.svg';
import postgresqlOriginal from 'url:../../images/devicon/postgresql-original.svg';
import postgresqlOriginalWordmark from 'url:../../images/devicon/postgresql-original-wordmark.svg';
import postgresqlPlain from 'url:../../images/devicon/postgresql-plain.svg';
import postgresqlPlainWordmark from 'url:../../images/devicon/postgresql-plain-wordmark.svg';
import premiereproOriginal from 'url:../../images/devicon/premierepro-original.svg';
import premiereproPlain from 'url:../../images/devicon/premierepro-plain.svg';
import processingOriginal from 'url:../../images/devicon/processing-original.svg';
import processingOriginalWordmark from 'url:../../images/devicon/processing-original-wordmark.svg';
import processingPlain from 'url:../../images/devicon/processing-plain.svg';
import processingPlainWordmark from 'url:../../images/devicon/processing-plain-wordmark.svg';
import prometheusOriginal from 'url:../../images/devicon/prometheus-original.svg';
import prometheusOriginalWordmark from 'url:../../images/devicon/prometheus-original-wordmark.svg';
import protractorPlain from 'url:../../images/devicon/protractor-plain.svg';
import protractorPlainWordmark from 'url:../../images/devicon/protractor-plain-wordmark.svg';
import puttyOriginal from 'url:../../images/devicon/putty-original.svg';
import puttyPlain from 'url:../../images/devicon/putty-plain.svg';
import pycharmOriginal from 'url:../../images/devicon/pycharm-original.svg';
import pycharmOriginalWordmark from 'url:../../images/devicon/pycharm-original-wordmark.svg';
import pycharmPlain from 'url:../../images/devicon/pycharm-plain.svg';
import pycharmPlainWordmark from 'url:../../images/devicon/pycharm-plain-wordmark.svg';
import pytestOriginal from 'url:../../images/devicon/pytest-original.svg';
import pytestOriginalWordmark from 'url:../../images/devicon/pytest-original-wordmark.svg';
import pytestPlain from 'url:../../images/devicon/pytest-plain.svg';
import pytestPlainWordmark from 'url:../../images/devicon/pytest-plain-wordmark.svg';
import pythonOriginal from 'url:../../images/devicon/python-original.svg';
import pythonOriginalWordmark from 'url:../../images/devicon/python-original-wordmark.svg';
import pythonPlain from 'url:../../images/devicon/python-plain.svg';
import pythonPlainWordmark from 'url:../../images/devicon/python-plain-wordmark.svg';
import pytorchOriginal from 'url:../../images/devicon/pytorch-original.svg';
import pytorchOriginalWordmark from 'url:../../images/devicon/pytorch-original-wordmark.svg';
import pytorchPlainWordmark from 'url:../../images/devicon/pytorch-plain-wordmark.svg';
import qtOriginal from 'url:../../images/devicon/qt-original.svg';
import rOriginal from 'url:../../images/devicon/r-original.svg';
import rPlain from 'url:../../images/devicon/r-plain.svg';
import railsOriginalWordmark from 'url:../../images/devicon/rails-original-wordmark.svg';
import railsPlain from 'url:../../images/devicon/rails-plain.svg';
import railsPlainWordmark from 'url:../../images/devicon/rails-plain-wordmark.svg';
import raspberrypiLine from 'url:../../images/devicon/raspberrypi-line.svg';
import raspberrypiLineWordmark from 'url:../../images/devicon/raspberrypi-line-wordmark.svg';
import raspberrypiOriginal from 'url:../../images/devicon/raspberrypi-original.svg';
import raspberrypiOriginalWordmark from 'url:../../images/devicon/raspberrypi-original-wordmark.svg';
import reactOriginal from 'url:../../images/devicon/react-original.svg';
import reactOriginalWordmark from 'url:../../images/devicon/react-original-wordmark.svg';
import rectOriginal from 'url:../../images/devicon/rect-original.svg';
import rectPlain from 'url:../../images/devicon/rect-plain.svg';
import redhatOriginal from 'url:../../images/devicon/redhat-original.svg';
import redhatOriginalWordmark from 'url:../../images/devicon/redhat-original-wordmark.svg';
import redhatPlain from 'url:../../images/devicon/redhat-plain.svg';
import redhatPlainWordmark from 'url:../../images/devicon/redhat-plain-wordmark.svg';
import redisOriginal from 'url:../../images/devicon/redis-original.svg';
import redisOriginalWordmark from 'url:../../images/devicon/redis-original-wordmark.svg';
import redisPlain from 'url:../../images/devicon/redis-plain.svg';
import redisPlainWordmark from 'url:../../images/devicon/redis-plain-wordmark.svg';
import reduxOriginal from 'url:../../images/devicon/redux-original.svg';
import rocksdbPlain from 'url:../../images/devicon/rocksdb-plain.svg';
import rspecOriginal from 'url:../../images/devicon/rspec-original.svg';
import rspecOriginalWordmark from 'url:../../images/devicon/rspec-original-wordmark.svg';
import rstudioOriginal from 'url:../../images/devicon/rstudio-original.svg';
import rstudioPlain from 'url:../../images/devicon/rstudio-plain.svg';
import rubyOriginal from 'url:../../images/devicon/ruby-original.svg';
import rubyOriginalWordmark from 'url:../../images/devicon/ruby-original-wordmark.svg';
import rubyPlain from 'url:../../images/devicon/ruby-plain.svg';
import rubyPlainWordmark from 'url:../../images/devicon/ruby-plain-wordmark.svg';
import rubymineOriginal from 'url:../../images/devicon/rubymine-original.svg';
import rubymineOriginalWordmark from 'url:../../images/devicon/rubymine-original-wordmark.svg';
import rubyminePlain from 'url:../../images/devicon/rubymine-plain.svg';
import rubyminePlainWordmark from 'url:../../images/devicon/rubymine-plain-wordmark.svg';
import rustPlain from 'url:../../images/devicon/rust-plain.svg';
import safariLine from 'url:../../images/devicon/safari-line.svg';
import safariLineWordmark from 'url:../../images/devicon/safari-line-wordmark.svg';
import safariOriginal from 'url:../../images/devicon/safari-original.svg';
import safariOriginalWordmark from 'url:../../images/devicon/safari-original-wordmark.svg';
import safariPlain from 'url:../../images/devicon/safari-plain.svg';
import safariPlainWordmark from 'url:../../images/devicon/safari-plain-wordmark.svg';
import salesforceOriginal from 'url:../../images/devicon/salesforce-original.svg';
import salesforcePlain from 'url:../../images/devicon/salesforce-plain.svg';
import sassOriginal from 'url:../../images/devicon/sass-original.svg';
import scalaOriginal from 'url:../../images/devicon/scala-original.svg';
import scalaOriginalWordmark from 'url:../../images/devicon/scala-original-wordmark.svg';
import scalaPlain from 'url:../../images/devicon/scala-plain.svg';
import scalaPlainWordmark from 'url:../../images/devicon/scala-plain-wordmark.svg';
import sdlOriginal from 'url:../../images/devicon/sdl-original.svg';
import sdlPlain from 'url:../../images/devicon/sdl-plain.svg';
import seleniumOriginal from 'url:../../images/devicon/selenium-original.svg';
import sequelizeOriginal from 'url:../../images/devicon/sequelize-original.svg';
import sequelizeOriginalWordmark from 'url:../../images/devicon/sequelize-original-wordmark.svg';
import sequelizePlain from 'url:../../images/devicon/sequelize-plain.svg';
import sequelizePlainWordmark from 'url:../../images/devicon/sequelize-plain-wordmark.svg';
import shopwareOriginal from 'url:../../images/devicon/shopware-original.svg';
import shopwareOriginalWordmark from 'url:../../images/devicon/shopware-original-wordmark.svg';
import shotgridOriginal from 'url:../../images/devicon/shotgrid-original.svg';
import shotgridOriginalWordmark from 'url:../../images/devicon/shotgrid-original-wordmark.svg';
import shotgridPlain from 'url:../../images/devicon/shotgrid-plain.svg';
import sketchLine from 'url:../../images/devicon/sketch-line.svg';
import sketchLineWordmark from 'url:../../images/devicon/sketch-line-wordmark.svg';
import sketchOriginal from 'url:../../images/devicon/sketch-original.svg';
import sketchOriginalWordmark from 'url:../../images/devicon/sketch-original-wordmark.svg';
import slackOriginal from 'url:../../images/devicon/slack-original.svg';
import slackOriginalWordmark from 'url:../../images/devicon/slack-original-wordmark.svg';
import slackPlain from 'url:../../images/devicon/slack-plain.svg';
import slackPlainWordmark from 'url:../../images/devicon/slack-plain-wordmark.svg';
import socketioOriginal from 'url:../../images/devicon/socketio-original.svg';
import socketioOriginalWordmark from 'url:../../images/devicon/socketio-original-wordmark.svg';
import solidityOriginal from 'url:../../images/devicon/solidity-original.svg';
import solidityPlain from 'url:../../images/devicon/solidity-plain.svg';
import sourcetreeOriginal from 'url:../../images/devicon/sourcetree-original.svg';
import sourcetreeOriginalWordmark from 'url:../../images/devicon/sourcetree-original-wordmark.svg';
import springOriginal from 'url:../../images/devicon/spring-original.svg';
import springOriginalWordmark from 'url:../../images/devicon/spring-original-wordmark.svg';
import springPlain from 'url:../../images/devicon/spring-plain.svg';
import springPlainWordmark from 'url:../../images/devicon/spring-plain-wordmark.svg';
import spssOriginal from 'url:../../images/devicon/spss-original.svg';
import spssPlain from 'url:../../images/devicon/spss-plain.svg';
import sqlalchemyOriginal from 'url:../../images/devicon/sqlalchemy-original.svg';
import sqlalchemyOriginalWordmark from 'url:../../images/devicon/sqlalchemy-original-wordmark.svg';
import sqlalchemyPlain from 'url:../../images/devicon/sqlalchemy-plain.svg';
import sqliteOriginal from 'url:../../images/devicon/sqlite-original.svg';
import sqliteOriginalWordmark from 'url:../../images/devicon/sqlite-original-wordmark.svg';
import sqlitePlain from 'url:../../images/devicon/sqlite-plain.svg';
import sqlitePlainWordmark from 'url:../../images/devicon/sqlite-plain-wordmark.svg';
import sshOriginal from 'url:../../images/devicon/ssh-original.svg';
import sshOriginalWordmark from 'url:../../images/devicon/ssh-original-wordmark.svg';
import storybookOriginal from 'url:../../images/devicon/storybook-original.svg';
import storybookOriginalWordmark from 'url:../../images/devicon/storybook-original-wordmark.svg';
import storybookPlain from 'url:../../images/devicon/storybook-plain.svg';
import storybookPlainWordmark from 'url:../../images/devicon/storybook-plain-wordmark.svg';
import stylusOriginal from 'url:../../images/devicon/stylus-original.svg';
import subversionOriginal from 'url:../../images/devicon/subversion-original.svg';
import subversionOriginalWordmark from 'url:../../images/devicon/subversion-original-wordmark.svg';
import svelteOriginal from 'url:../../images/devicon/svelte-original.svg';
import svelteOriginalWordmark from 'url:../../images/devicon/svelte-original-wordmark.svg';
import sveltePlain from 'url:../../images/devicon/svelte-plain.svg';
import sveltePlainWordmark from 'url:../../images/devicon/svelte-plain-wordmark.svg';
import swiftOriginal from 'url:../../images/devicon/swift-original.svg';
import swiftOriginalWordmark from 'url:../../images/devicon/swift-original-wordmark.svg';
import swiftPlain from 'url:../../images/devicon/swift-plain.svg';
import swiftPlainWordmark from 'url:../../images/devicon/swift-plain-wordmark.svg';
import symfonyOriginal from 'url:../../images/devicon/symfony-original.svg';
import symfonyOriginalWordmark from 'url:../../images/devicon/symfony-original-wordmark.svg';
import tailwindcssOriginalWordmark from 'url:../../images/devicon/tailwindcss-original-wordmark.svg';
import tailwindcssPlain from 'url:../../images/devicon/tailwindcss-plain.svg';
import tensorflowLine from 'url:../../images/devicon/tensorflow-line.svg';
import tensorflowLineWordmark from 'url:../../images/devicon/tensorflow-line-wordmark.svg';
import tensorflowOriginal from 'url:../../images/devicon/tensorflow-original.svg';
import tensorflowOriginalWordmark from 'url:../../images/devicon/tensorflow-original-wordmark.svg';
import terraformOriginal from 'url:../../images/devicon/terraform-original.svg';
import terraformOriginalWordmark from 'url:../../images/devicon/terraform-original-wordmark.svg';
import terraformPlain from 'url:../../images/devicon/terraform-plain.svg';
import terraformPlainWordmark from 'url:../../images/devicon/terraform-plain-wordmark.svg';
import thealgorithmsOriginal from 'url:../../images/devicon/thealgorithms-original.svg';
import thealgorithmsOriginalWordmark from 'url:../../images/devicon/thealgorithms-original-wordmark.svg';
import thealgorithmsPlain from 'url:../../images/devicon/thealgorithms-plain.svg';
import thealgorithmsPlainWordmark from 'url:../../images/devicon/thealgorithms-plain-wordmark.svg';
import threejsOriginal from 'url:../../images/devicon/threejs-original.svg';
import threejsOriginalWordmark from 'url:../../images/devicon/threejs-original-wordmark.svg';
import tomcatLine from 'url:../../images/devicon/tomcat-line.svg';
import tomcatLineWordmark from 'url:../../images/devicon/tomcat-line-wordmark.svg';
import tomcatOriginal from 'url:../../images/devicon/tomcat-original.svg';
import tomcatOriginalWordmark from 'url:../../images/devicon/tomcat-original-wordmark.svg';
import tortoisegitLine from 'url:../../images/devicon/tortoisegit-line.svg';
import tortoisegitOriginal from 'url:../../images/devicon/tortoisegit-original.svg';
import tortoisegitPlain from 'url:../../images/devicon/tortoisegit-plain.svg';
import towergitOriginal from 'url:../../images/devicon/towergit-original.svg';
import towergitOriginalWordmark from 'url:../../images/devicon/towergit-original-wordmark.svg';
import towergitPlain from 'url:../../images/devicon/towergit-plain.svg';
import towergitPlainWordmark from 'url:../../images/devicon/towergit-plain-wordmark.svg';
import travisPlain from 'url:../../images/devicon/travis-plain.svg';
import travisPlainWordmark from 'url:../../images/devicon/travis-plain-wordmark.svg';
import trelloPlain from 'url:../../images/devicon/trello-plain.svg';
import trelloPlainWordmark from 'url:../../images/devicon/trello-plain-wordmark.svg';
import twitterOriginal from 'url:../../images/devicon/twitter-original.svg';
import typescriptOriginal from 'url:../../images/devicon/typescript-original.svg';
import typescriptPlain from 'url:../../images/devicon/typescript-plain.svg';
import typo3Original from 'url:../../images/devicon/typo3-original.svg';
import typo3OriginalWordmark from 'url:../../images/devicon/typo3-original-wordmark.svg';
import typo3Plain from 'url:../../images/devicon/typo3-plain.svg';
import typo3PlainWordmark from 'url:../../images/devicon/typo3-plain-wordmark.svg';
import ubuntuPlain from 'url:../../images/devicon/ubuntu-plain.svg';
import ubuntuPlainWordmark from 'url:../../images/devicon/ubuntu-plain-wordmark.svg';
import unityOriginal from 'url:../../images/devicon/unity-original.svg';
import unityOriginalWordmark from 'url:../../images/devicon/unity-original-wordmark.svg';
import unixOriginal from 'url:../../images/devicon/unix-original.svg';
import unrealengineOriginal from 'url:../../images/devicon/unrealengine-original.svg';
import unrealengineOriginalWordmark from 'url:../../images/devicon/unrealengine-original-wordmark.svg';
import uwsgiOriginal from 'url:../../images/devicon/uwsgi-original.svg';
import uwsgiPlain from 'url:../../images/devicon/uwsgi-plain.svg';
import vagrantOriginal from 'url:../../images/devicon/vagrant-original.svg';
import vagrantOriginalWordmark from 'url:../../images/devicon/vagrant-original-wordmark.svg';
import vagrantPlain from 'url:../../images/devicon/vagrant-plain.svg';
import vagrantPlainWordmark from 'url:../../images/devicon/vagrant-plain-wordmark.svg';
import vimOriginal from 'url:../../images/devicon/vim-original.svg';
import vimPlain from 'url:../../images/devicon/vim-plain.svg';
import visualstudioPlain from 'url:../../images/devicon/visualstudio-plain.svg';
import visualstudioPlainWordmark from 'url:../../images/devicon/visualstudio-plain-wordmark.svg';
import vscodeOriginal from 'url:../../images/devicon/vscode-original.svg';
import vscodeOriginalWordmark from 'url:../../images/devicon/vscode-original-wordmark.svg';
import vscodePlain from 'url:../../images/devicon/vscode-plain.svg';
import vscodePlainWordmark from 'url:../../images/devicon/vscode-plain-wordmark.svg';
import vuejsLine from 'url:../../images/devicon/vuejs-line.svg';
import vuejsLineWordmark from 'url:../../images/devicon/vuejs-line-wordmark.svg';
import vuejsOriginal from 'url:../../images/devicon/vuejs-original.svg';
import vuejsOriginalWordmark from 'url:../../images/devicon/vuejs-original-wordmark.svg';
import vuejsPlain from 'url:../../images/devicon/vuejs-plain.svg';
import vuejsPlainWordmark from 'url:../../images/devicon/vuejs-plain-wordmark.svg';
import vuestorefrontOriginal from 'url:../../images/devicon/vuestorefront-original.svg';
import vuestorefrontPlain from 'url:../../images/devicon/vuestorefront-plain.svg';
import vuetifyLine from 'url:../../images/devicon/vuetify-line.svg';
import vuetifyOriginal from 'url:../../images/devicon/vuetify-original.svg';
import vuetifyPlain from 'url:../../images/devicon/vuetify-plain.svg';
import webflowOriginal from 'url:../../images/devicon/webflow-original.svg';
import weblateOriginal from 'url:../../images/devicon/weblate-original.svg';
import weblateOriginalWordmark from 'url:../../images/devicon/weblate-original-wordmark.svg';
import weblatePlain from 'url:../../images/devicon/weblate-plain.svg';
import weblatePlainWordmark from 'url:../../images/devicon/weblate-plain-wordmark.svg';
import webpackOriginal from 'url:../../images/devicon/webpack-original.svg';
import webpackOriginalWordmark from 'url:../../images/devicon/webpack-original-wordmark.svg';
import webpackPlain from 'url:../../images/devicon/webpack-plain.svg';
import webpackPlainWordmark from 'url:../../images/devicon/webpack-plain-wordmark.svg';
import webstormOriginal from 'url:../../images/devicon/webstorm-original.svg';
import webstormOriginalWordmark from 'url:../../images/devicon/webstorm-original-wordmark.svg';
import webstormPlain from 'url:../../images/devicon/webstorm-plain.svg';
import webstormPlainWordmark from 'url:../../images/devicon/webstorm-plain-wordmark.svg';
import windows8Original from 'url:../../images/devicon/windows8-original.svg';
import windows8OriginalWordmark from 'url:../../images/devicon/windows8-original-wordmark.svg';
import woocommerceOriginal from 'url:../../images/devicon/woocommerce-original.svg';
import woocommerceOriginalWordmark from 'url:../../images/devicon/woocommerce-original-wordmark.svg';
import woocommercePlain from 'url:../../images/devicon/woocommerce-plain.svg';
import woocommercePlainWordmark from 'url:../../images/devicon/woocommerce-plain-wordmark.svg';
import wordpressOriginal from 'url:../../images/devicon/wordpress-original.svg';
import wordpressPlain from 'url:../../images/devicon/wordpress-plain.svg';
import wordpressPlainWordmark from 'url:../../images/devicon/wordpress-plain-wordmark.svg';
import xamarinOriginal from 'url:../../images/devicon/xamarin-original.svg';
import xamarinOriginalWordmark from 'url:../../images/devicon/xamarin-original-wordmark.svg';
import xcodeOriginal from 'url:../../images/devicon/xcode-original.svg';
import xcodePlain from 'url:../../images/devicon/xcode-plain.svg';
import xdLine from 'url:../../images/devicon/xd-line.svg';
import xdPlain from 'url:../../images/devicon/xd-plain.svg';
import yarnOriginal from 'url:../../images/devicon/yarn-original.svg';
import yarnOriginalWordmark from 'url:../../images/devicon/yarn-original-wordmark.svg';
import yiiOriginal from 'url:../../images/devicon/yii-original.svg';
import yiiOriginalWordmark from 'url:../../images/devicon/yii-original-wordmark.svg';
import yiiPlain from 'url:../../images/devicon/yii-plain.svg';
import yiiPlainWordmark from 'url:../../images/devicon/yii-plain-wordmark.svg';
import yunohostOriginal from 'url:../../images/devicon/yunohost-original.svg';
import yunohostPlain from 'url:../../images/devicon/yunohost-plain.svg';
import zendPlain from 'url:../../images/devicon/zend-plain.svg';
import zendPlainWordmark from 'url:../../images/devicon/zend-plain-wordmark.svg';
import zigOriginal from 'url:../../images/devicon/zig-original.svg';
import zigOriginalWordmark from 'url:../../images/devicon/zig-original-wordmark.svg';
import zigPlainWordmark from 'url:../../images/devicon/zig-plain-wordmark.svg';

export {
  aarch64Original,
  aarch64Plain,
  adonisjsOriginal,
  adonisjsOriginalWordmark,
  aftereffectsOriginal,
  aftereffectsPlain,
  amazonwebservicesOriginal,
  amazonwebservicesOriginalWordmark,
  amazonwebservicesPlainWordmark,
  anacondaOriginal,
  anacondaOriginalWordmark,
  androidOriginal,
  androidOriginalWordmark,
  androidPlain,
  androidPlainWordmark,
  androidstudioOriginal,
  androidstudioOriginalWordmark,
  androidstudioPlain,
  androidstudioPlainWordmark,
  angularjsOriginal,
  angularjsOriginalWordmark,
  angularjsPlain,
  angularjsPlainWordmark,
  ansibleOriginal,
  ansibleOriginalWordmark,
  ansiblePlain,
  ansiblePlainWordmark,
  apacheLine,
  apacheLineWordmark,
  apacheOriginal,
  apacheOriginalWordmark,
  apachePlain,
  apachePlainWordmark,
  apachekafkaOriginal,
  apachekafkaOriginalWordmark,
  appceleratorOriginal,
  appceleratorOriginalWordmark,
  appceleratorPlainWordmark,
  appleOriginal,
  appwriteOriginal,
  appwriteOriginalWordmark,
  appwritePlain,
  appwritePlainWordmark,
  arduinoOriginal,
  arduinoOriginalWordmark,
  arduinoPlain,
  arduinoPlainWordmark,
  argocdOriginal,
  argocdOriginalWordmark,
  argocdPlain,
  argocdPlainWordmark,
  atomOriginal,
  atomOriginalWordmark,
  azureOriginal,
  azureOriginalWordmark,
  azurePlain,
  azurePlainWordmark,
  babelOriginal,
  babelPlain,
  backbonejsOriginal,
  backbonejsOriginalWordmark,
  backbonejsPlain,
  backbonejsPlainWordmark,
  bambooOriginal,
  bambooOriginalWordmark,
  bashOriginal,
  bashPlain,
  behanceOriginal,
  behanceOriginalWordmark,
  behancePlain,
  behancePlainWordmark,
  bitbucketOriginal,
  bitbucketOriginalWordmark,
  blenderOriginal,
  blenderOriginalWordmark,
  bootstrapOriginal,
  bootstrapOriginalWordmark,
  bootstrapPlain,
  bootstrapPlainWordmark,
  bowerLine,
  bowerLineWordmark,
  bowerOriginal,
  bowerOriginalWordmark,
  bowerPlain,
  bowerPlainWordmark,
  bulmaPlain,
  cLine,
  cOriginal,
  cPlain,
  cakephpOriginal,
  cakephpOriginalWordmark,
  cakephpPlain,
  cakephpPlainWordmark,
  canvaOriginal,
  centosOriginal,
  centosOriginalWordmark,
  centosPlain,
  centosPlainWordmark,
  ceylonOriginal,
  ceylonOriginalWordmark,
  ceylonPlain,
  ceylonPlainWordmark,
  chromeOriginal,
  chromeOriginalWordmark,
  chromePlain,
  chromePlainWordmark,
  circleciPlain,
  circleciPlainWordmark,
  clojureLine,
  clojureOriginal,
  clojurescriptOriginal,
  clojurescriptPlain,
  cmakeOriginal,
  cmakeOriginalWordmark,
  cmakePlain,
  cmakePlainWordmark,
  codecovPlain,
  codeigniterPlain,
  codeigniterPlainWordmark,
  codepenOriginalWordmark,
  codepenPlain,
  coffeescriptOriginal,
  coffeescriptOriginalWordmark,
  composerLine,
  composerLineWordmark,
  composerOriginal,
  confluenceOriginal,
  confluenceOriginalWordmark,
  couchdbOriginal,
  couchdbOriginalWordmark,
  couchdbPlain,
  couchdbPlainWordmark,
  cplusplusLine,
  cplusplusOriginal,
  cplusplusPlain,
  crystalOriginal,
  crystalOriginalWordmark,
  csharpLine,
  csharpOriginal,
  csharpPlain,
  css3Original,
  css3OriginalWordmark,
  css3Plain,
  css3PlainWordmark,
  cucumberPlain,
  cucumberPlainWordmark,
  d3JsOriginal,
  d3JsPlain,
  dartOriginal,
  dartOriginalWordmark,
  dartPlain,
  dartPlainWordmark,
  debianOriginal,
  debianOriginalWordmark,
  debianPlain,
  debianPlainWordmark,
  denojsOriginal,
  denojsOriginalWordmark,
  deviconLine,
  deviconLineWordmark,
  deviconOriginal,
  deviconOriginalWordmark,
  deviconPlain,
  deviconPlainWordmark,
  digitaloceanOriginal,
  digitaloceanOriginalWordmark,
  digitaloceanPlain,
  digitaloceanPlainWordmark,
  discordjsOriginal,
  discordjsOriginalWordmark,
  discordjsPlain,
  discordjsPlainWordmark,
  djangoPlain,
  djangoPlainWordmark,
  dockerOriginal,
  dockerOriginalWordmark,
  dockerPlain,
  dockerPlainWordmark,
  doctrineLine,
  doctrineLineWordmark,
  doctrineOriginal,
  doctrineOriginalWordmark,
  doctrinePlain,
  doctrinePlainWordmark,
  dotNetOriginal,
  dotNetOriginalWordmark,
  dotNetPlain,
  dotNetPlainWordmark,
  dotnetcoreOriginal,
  dotnetcorePlain,
  dropwizardOriginal,
  dropwizardPlain,
  drupalOriginal,
  drupalOriginalWordmark,
  drupalPlain,
  drupalPlainWordmark,
  electronOriginal,
  electronOriginalWordmark,
  eleventyOriginal,
  eleventyPlain,
  elixirOriginal,
  elixirOriginalWordmark,
  elixirPlain,
  elixirPlainWordmark,
  elmOriginal,
  elmOriginalWordmark,
  elmPlain,
  elmPlainWordmark,
  embeddedcOriginal,
  embeddedcOriginalWordmark,
  embeddedcPlain,
  embeddedcPlainWordmark,
  emberOriginalWordmark,
  erlangOriginal,
  erlangOriginalWordmark,
  erlangPlain,
  erlangPlainWordmark,
  eslintOriginal,
  eslintOriginalWordmark,
  expressOriginal,
  expressOriginalWordmark,
  facebookOriginal,
  facebookPlain,
  fastapiOriginal,
  fastapiOriginalWordmark,
  fastapiPlain,
  fastapiPlainWordmark,
  feathersjsOriginal,
  fedoraOriginal,
  fedoraPlain,
  figmaOriginal,
  figmaPlain,
  filezillaPlain,
  filezillaPlainWordmark,
  firebasePlain,
  firebasePlainWordmark,
  firefoxOriginal,
  firefoxOriginalWordmark,
  firefoxPlain,
  firefoxPlainWordmark,
  flaskOriginal,
  flaskOriginalWordmark,
  flutterOriginal,
  flutterPlain,
  foundationOriginal,
  foundationOriginalWordmark,
  foundationPlain,
  foundationPlainWordmark,
  fsharpOriginal,
  fsharpPlain,
  gatlingPlain,
  gatlingPlainWordmark,
  gatsbyOriginal,
  gatsbyOriginalWordmark,
  gatsbyPlain,
  gatsbyPlainWordmark,
  gccOriginal,
  gccPlain,
  gentooPlain,
  gentooPlainWordmark,
  gimpOriginal,
  gimpOriginalWordmark,
  gimpPlain,
  gimpPlainWordmark,
  gitOriginal,
  gitOriginalWordmark,
  gitPlain,
  gitPlainWordmark,
  githubOriginal,
  githubOriginalWordmark,
  gitlabOriginal,
  gitlabOriginalWordmark,
  gitlabPlain,
  gitlabPlainWordmark,
  gitterPlain,
  gitterPlainWordmark,
  goLine,
  goOriginal,
  goOriginalWordmark,
  goPlain,
  godotOriginal,
  godotOriginalWordmark,
  godotPlain,
  godotPlainWordmark,
  googleOriginal,
  googleOriginalWordmark,
  googlePlain,
  googlePlainWordmark,
  googlecloudOriginal,
  googlecloudOriginalWordmark,
  googlecloudPlain,
  googlecloudPlainWordmark,
  gradlePlain,
  gradlePlainWordmark,
  grafanaOriginal,
  grafanaOriginalWordmark,
  grailsOriginal,
  grailsPlain,
  graphqlPlain,
  graphqlPlainWordmark,
  groovyOriginal,
  groovyPlain,
  gruntLine,
  gruntLineWordmark,
  gruntOriginal,
  gruntOriginalWordmark,
  gruntPlain,
  gruntPlainWordmark,
  gulpPlain,
  handlebarsOriginal,
  handlebarsOriginalWordmark,
  haskellOriginal,
  haskellOriginalWordmark,
  haskellPlain,
  haskellPlainWordmark,
  haxeOriginal,
  haxePlain,
  herokuOriginal,
  herokuOriginalWordmark,
  herokuPlain,
  herokuPlainWordmark,
  html5Original,
  html5OriginalWordmark,
  html5Plain,
  html5PlainWordmark,
  hugoOriginal,
  hugoOriginalWordmark,
  hugoPlain,
  hugoPlainWordmark,
  ie10Original,
  iftttOriginal,
  illustratorLine,
  illustratorPlain,
  inkscapeOriginal,
  inkscapeOriginalWordmark,
  inkscapePlain,
  inkscapePlainWordmark,
  intellijOriginal,
  intellijOriginalWordmark,
  intellijPlain,
  intellijPlainWordmark,
  ionicOriginal,
  ionicOriginalWordmark,
  jamstackOriginal,
  jamstackOriginalWordmark,
  jamstackPlainWordmark,
  jasminePlain,
  jasminePlainWordmark,
  javaOriginal,
  javaOriginalWordmark,
  javaPlain,
  javaPlainWordmark,
  javascriptOriginal,
  javascriptPlain,
  jeetOriginal,
  jeetOriginalWordmark,
  jeetPlain,
  jeetPlainWordmark,
  jenkinsLine,
  jenkinsOriginal,
  jenkinsPlain,
  jestPlain,
  jetbrainsOriginal,
  jetbrainsPlain,
  jiraOriginal,
  jiraOriginalWordmark,
  jiraPlain,
  jiraPlainWordmark,
  jqueryOriginal,
  jqueryOriginalWordmark,
  jqueryPlain,
  jqueryPlainWordmark,
  juliaOriginal,
  juliaOriginalWordmark,
  juliaPlain,
  juliaPlainWordmark,
  jupyterOriginal,
  jupyterOriginalWordmark,
  jupyterPlain,
  jupyterPlainWordmark,
  k3SOriginal,
  k3SOriginalWordmark,
  k3SPlainWordmark,
  kaggleOriginal,
  kaggleOriginalWordmark,
  karmaOriginal,
  karmaPlain,
  knockoutPlainWordmark,
  kotlinOriginal,
  kotlinOriginalWordmark,
  kotlinPlain,
  kotlinPlainWordmark,
  krakenjsOriginal,
  krakenjsOriginalWordmark,
  krakenjsPlain,
  krakenjsPlainWordmark,
  kubernetesPlain,
  kubernetesPlainWordmark,
  labviewOriginal,
  labviewOriginalWordmark,
  labviewPlain,
  labviewPlainWordmark,
  laravelPlain,
  laravelPlainWordmark,
  latexOriginal,
  lessPlainWordmark,
  linkedinOriginal,
  linkedinOriginalWordmark,
  linkedinPlain,
  linkedinPlainWordmark,
  linuxOriginal,
  linuxPlain,
  luaOriginal,
  luaOriginalWordmark,
  luaPlain,
  luaPlainWordmark,
  magentoLine,
  magentoOriginal,
  magentoOriginalWordmark,
  markdownOriginal,
  materialuiOriginal,
  materialuiPlain,
  matlabLine,
  matlabOriginal,
  matlabPlain,
  mayaOriginal,
  mayaOriginalWordmark,
  mayaPlain,
  mayaPlainWordmark,
  meteorOriginal,
  meteorOriginalWordmark,
  meteorPlain,
  meteorPlainWordmark,
  microsoftsqlserverPlain,
  microsoftsqlserverPlainWordmark,
  minitabOriginal,
  minitabPlain,
  mochaPlain,
  modxOriginal,
  modxOriginalWordmark,
  modxPlain,
  modxPlainWordmark,
  mongodbOriginal,
  mongodbOriginalWordmark,
  mongodbPlain,
  mongodbPlainWordmark,
  moodleOriginal,
  moodleOriginalWordmark,
  moodlePlain,
  moodlePlainWordmark,
  msdosLine,
  msdosOriginal,
  msdosPlain,
  mysqlOriginal,
  mysqlOriginalWordmark,
  mysqlPlain,
  mysqlPlainWordmark,
  neo4JOriginal,
  neo4JOriginalWordmark,
  neo4JPlain,
  neo4JPlainWordmark,
  nestjsPlain,
  nestjsPlainWordmark,
  networkxOriginal,
  nextjsLine,
  nextjsOriginal,
  nextjsOriginalWordmark,
  nginxOriginal,
  nixosOriginal,
  nixosOriginalWordmark,
  nixosPlain,
  nixosPlainWordmark,
  nodejsOriginal,
  nodejsOriginalWordmark,
  nodejsPlain,
  nodejsPlainWordmark,
  nodewebkitLine,
  nodewebkitLineWordmark,
  nodewebkitOriginal,
  nodewebkitOriginalWordmark,
  nodewebkitPlain,
  nodewebkitPlainWordmark,
  npmOriginalWordmark,
  nugetOriginal,
  nugetOriginalWordmark,
  numpyOriginal,
  numpyOriginalWordmark,
  nuxtjsOriginal,
  nuxtjsOriginalWordmark,
  nuxtjsPlain,
  nuxtjsPlainWordmark,
  objectivecPlain,
  ocamlOriginal,
  ocamlOriginalWordmark,
  ocamlPlain,
  ocamlPlainWordmark,
  openalOriginal,
  openalPlain,
  opencvOriginal,
  opencvOriginalWordmark,
  opencvPlain,
  opencvPlainWordmark,
  openglOriginal,
  openglPlain,
  opensuseOriginal,
  opensuseOriginalWordmark,
  opensusePlain,
  opensusePlainWordmark,
  operaOriginal,
  operaOriginalWordmark,
  operaPlain,
  operaPlainWordmark,
  oracleOriginal,
  packerOriginal,
  packerOriginalWordmark,
  pandasOriginal,
  pandasOriginalWordmark,
  perlOriginal,
  perlPlain,
  phalconOriginal,
  phalconPlain,
  phoenixOriginal,
  phoenixOriginalWordmark,
  phoenixPlain,
  phoenixPlainWordmark,
  photoshopLine,
  photoshopPlain,
  phpOriginal,
  phpPlain,
  phpstormOriginal,
  phpstormOriginalWordmark,
  phpstormPlain,
  phpstormPlainWordmark,
  podmanOriginal,
  podmanOriginalWordmark,
  podmanPlain,
  podmanPlainWordmark,
  polygonOriginal,
  polygonPlain,
  postgresqlOriginal,
  postgresqlOriginalWordmark,
  postgresqlPlain,
  postgresqlPlainWordmark,
  premiereproOriginal,
  premiereproPlain,
  processingOriginal,
  processingOriginalWordmark,
  processingPlain,
  processingPlainWordmark,
  prometheusOriginal,
  prometheusOriginalWordmark,
  protractorPlain,
  protractorPlainWordmark,
  puttyOriginal,
  puttyPlain,
  pycharmOriginal,
  pycharmOriginalWordmark,
  pycharmPlain,
  pycharmPlainWordmark,
  pytestOriginal,
  pytestOriginalWordmark,
  pytestPlain,
  pytestPlainWordmark,
  pythonOriginal,
  pythonOriginalWordmark,
  pythonPlain,
  pythonPlainWordmark,
  pytorchOriginal,
  pytorchOriginalWordmark,
  pytorchPlainWordmark,
  qtOriginal,
  rOriginal,
  rPlain,
  railsOriginalWordmark,
  railsPlain,
  railsPlainWordmark,
  raspberrypiLine,
  raspberrypiLineWordmark,
  raspberrypiOriginal,
  raspberrypiOriginalWordmark,
  reactOriginal,
  reactOriginalWordmark,
  rectOriginal,
  rectPlain,
  redhatOriginal,
  redhatOriginalWordmark,
  redhatPlain,
  redhatPlainWordmark,
  redisOriginal,
  redisOriginalWordmark,
  redisPlain,
  redisPlainWordmark,
  reduxOriginal,
  rocksdbPlain,
  rspecOriginal,
  rspecOriginalWordmark,
  rstudioOriginal,
  rstudioPlain,
  rubyOriginal,
  rubyOriginalWordmark,
  rubyPlain,
  rubyPlainWordmark,
  rubymineOriginal,
  rubymineOriginalWordmark,
  rubyminePlain,
  rubyminePlainWordmark,
  rustPlain,
  safariLine,
  safariLineWordmark,
  safariOriginal,
  safariOriginalWordmark,
  safariPlain,
  safariPlainWordmark,
  salesforceOriginal,
  salesforcePlain,
  sassOriginal,
  scalaOriginal,
  scalaOriginalWordmark,
  scalaPlain,
  scalaPlainWordmark,
  sdlOriginal,
  sdlPlain,
  seleniumOriginal,
  sequelizeOriginal,
  sequelizeOriginalWordmark,
  sequelizePlain,
  sequelizePlainWordmark,
  shopwareOriginal,
  shopwareOriginalWordmark,
  shotgridOriginal,
  shotgridOriginalWordmark,
  shotgridPlain,
  sketchLine,
  sketchLineWordmark,
  sketchOriginal,
  sketchOriginalWordmark,
  slackOriginal,
  slackOriginalWordmark,
  slackPlain,
  slackPlainWordmark,
  socketioOriginal,
  socketioOriginalWordmark,
  solidityOriginal,
  solidityPlain,
  sourcetreeOriginal,
  sourcetreeOriginalWordmark,
  springOriginal,
  springOriginalWordmark,
  springPlain,
  springPlainWordmark,
  spssOriginal,
  spssPlain,
  sqlalchemyOriginal,
  sqlalchemyOriginalWordmark,
  sqlalchemyPlain,
  sqliteOriginal,
  sqliteOriginalWordmark,
  sqlitePlain,
  sqlitePlainWordmark,
  sshOriginal,
  sshOriginalWordmark,
  storybookOriginal,
  storybookOriginalWordmark,
  storybookPlain,
  storybookPlainWordmark,
  stylusOriginal,
  subversionOriginal,
  subversionOriginalWordmark,
  svelteOriginal,
  svelteOriginalWordmark,
  sveltePlain,
  sveltePlainWordmark,
  swiftOriginal,
  swiftOriginalWordmark,
  swiftPlain,
  swiftPlainWordmark,
  symfonyOriginal,
  symfonyOriginalWordmark,
  tailwindcssOriginalWordmark,
  tailwindcssPlain,
  tensorflowLine,
  tensorflowLineWordmark,
  tensorflowOriginal,
  tensorflowOriginalWordmark,
  terraformOriginal,
  terraformOriginalWordmark,
  terraformPlain,
  terraformPlainWordmark,
  thealgorithmsOriginal,
  thealgorithmsOriginalWordmark,
  thealgorithmsPlain,
  thealgorithmsPlainWordmark,
  threejsOriginal,
  threejsOriginalWordmark,
  tomcatLine,
  tomcatLineWordmark,
  tomcatOriginal,
  tomcatOriginalWordmark,
  tortoisegitLine,
  tortoisegitOriginal,
  tortoisegitPlain,
  towergitOriginal,
  towergitOriginalWordmark,
  towergitPlain,
  towergitPlainWordmark,
  travisPlain,
  travisPlainWordmark,
  trelloPlain,
  trelloPlainWordmark,
  twitterOriginal,
  typescriptOriginal,
  typescriptPlain,
  typo3Original,
  typo3OriginalWordmark,
  typo3Plain,
  typo3PlainWordmark,
  ubuntuPlain,
  ubuntuPlainWordmark,
  unityOriginal,
  unityOriginalWordmark,
  unixOriginal,
  unrealengineOriginal,
  unrealengineOriginalWordmark,
  uwsgiOriginal,
  uwsgiPlain,
  vagrantOriginal,
  vagrantOriginalWordmark,
  vagrantPlain,
  vagrantPlainWordmark,
  vimOriginal,
  vimPlain,
  visualstudioPlain,
  visualstudioPlainWordmark,
  vscodeOriginal,
  vscodeOriginalWordmark,
  vscodePlain,
  vscodePlainWordmark,
  vuejsLine,
  vuejsLineWordmark,
  vuejsOriginal,
  vuejsOriginalWordmark,
  vuejsPlain,
  vuejsPlainWordmark,
  vuestorefrontOriginal,
  vuestorefrontPlain,
  vuetifyLine,
  vuetifyOriginal,
  vuetifyPlain,
  webflowOriginal,
  weblateOriginal,
  weblateOriginalWordmark,
  weblatePlain,
  weblatePlainWordmark,
  webpackOriginal,
  webpackOriginalWordmark,
  webpackPlain,
  webpackPlainWordmark,
  webstormOriginal,
  webstormOriginalWordmark,
  webstormPlain,
  webstormPlainWordmark,
  windows8Original,
  windows8OriginalWordmark,
  woocommerceOriginal,
  woocommerceOriginalWordmark,
  woocommercePlain,
  woocommercePlainWordmark,
  wordpressOriginal,
  wordpressPlain,
  wordpressPlainWordmark,
  xamarinOriginal,
  xamarinOriginalWordmark,
  xcodeOriginal,
  xcodePlain,
  xdLine,
  xdPlain,
  yarnOriginal,
  yarnOriginalWordmark,
  yiiOriginal,
  yiiOriginalWordmark,
  yiiPlain,
  yiiPlainWordmark,
  yunohostOriginal,
  yunohostPlain,
  zendPlain,
  zendPlainWordmark,
  zigOriginal,
  zigOriginalWordmark,
  zigPlainWordmark,
};
